[package]
name = "open_gl_triangle"
version = "0.1.0"
authors = ["Youngermaster <juanmanuel12.13jmyh81@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.14.0"
glutin = "0.25"

[build-dependencies]
gl_generator = "0.14.0"
