[package]
name = "actix-simple-mongo"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
actix-rt = "2.0.0"
mongodb = "2.0.0"
bson = "2.6.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
dotenv = "0.15.0"