[package]
name = "blinking-led-raspberry-pi"
version = "0.1.0"
authors = ["Youngermaster <jmyoungh@eafit.edu.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_gpiozero = "0.2.0"